/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SurveyIndexRouteImport } from './routes/survey.index'
import { Route as SurveyAdminRouteImport } from './routes/survey.admin'
import { Route as SurveySpotsNewRouteImport } from './routes/survey.spots.new'
import { Route as SurveySpotsIdIndexRouteImport } from './routes/survey.spots.$id.index'
import { Route as SurveySpotsIdSectionRouteImport } from './routes/survey.spots.$id.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIndexRoute = SurveyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveyRoute,
} as any)
const SurveyAdminRoute = SurveyAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SurveyRoute,
} as any)
const SurveySpotsNewRoute = SurveySpotsNewRouteImport.update({
  id: '/spots/new',
  path: '/spots/new',
  getParentRoute: () => SurveyRoute,
} as any)
const SurveySpotsIdIndexRoute = SurveySpotsIdIndexRouteImport.update({
  id: '/spots/$id/',
  path: '/spots/$id/',
  getParentRoute: () => SurveyRoute,
} as any)
const SurveySpotsIdSectionRoute = SurveySpotsIdSectionRouteImport.update({
  id: '/spots/$id/$section',
  path: '/spots/$id/$section',
  getParentRoute: () => SurveyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survey': typeof SurveyRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/survey/admin': typeof SurveyAdminRoute
  '/survey/': typeof SurveyIndexRoute
  '/survey/spots/new': typeof SurveySpotsNewRoute
  '/survey/spots/$id/$section': typeof SurveySpotsIdSectionRoute
  '/survey/spots/$id/': typeof SurveySpotsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/survey/admin': typeof SurveyAdminRoute
  '/survey': typeof SurveyIndexRoute
  '/survey/spots/new': typeof SurveySpotsNewRoute
  '/survey/spots/$id/$section': typeof SurveySpotsIdSectionRoute
  '/survey/spots/$id': typeof SurveySpotsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/survey': typeof SurveyRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/survey/admin': typeof SurveyAdminRoute
  '/survey/': typeof SurveyIndexRoute
  '/survey/spots/new': typeof SurveySpotsNewRoute
  '/survey/spots/$id/$section': typeof SurveySpotsIdSectionRoute
  '/survey/spots/$id/': typeof SurveySpotsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/survey'
    | '/invite/$token'
    | '/survey/admin'
    | '/survey/'
    | '/survey/spots/new'
    | '/survey/spots/$id/$section'
    | '/survey/spots/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/survey/admin'
    | '/survey'
    | '/survey/spots/new'
    | '/survey/spots/$id/$section'
    | '/survey/spots/$id'
  id:
    | '__root__'
    | '/'
    | '/survey'
    | '/invite/$token'
    | '/survey/admin'
    | '/survey/'
    | '/survey/spots/new'
    | '/survey/spots/$id/$section'
    | '/survey/spots/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurveyRoute: typeof SurveyRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/': {
      id: '/survey/'
      path: '/'
      fullPath: '/survey/'
      preLoaderRoute: typeof SurveyIndexRouteImport
      parentRoute: typeof SurveyRoute
    }
    '/survey/admin': {
      id: '/survey/admin'
      path: '/admin'
      fullPath: '/survey/admin'
      preLoaderRoute: typeof SurveyAdminRouteImport
      parentRoute: typeof SurveyRoute
    }
    '/survey/spots/new': {
      id: '/survey/spots/new'
      path: '/spots/new'
      fullPath: '/survey/spots/new'
      preLoaderRoute: typeof SurveySpotsNewRouteImport
      parentRoute: typeof SurveyRoute
    }
    '/survey/spots/$id/': {
      id: '/survey/spots/$id/'
      path: '/spots/$id'
      fullPath: '/survey/spots/$id/'
      preLoaderRoute: typeof SurveySpotsIdIndexRouteImport
      parentRoute: typeof SurveyRoute
    }
    '/survey/spots/$id/$section': {
      id: '/survey/spots/$id/$section'
      path: '/spots/$id/$section'
      fullPath: '/survey/spots/$id/$section'
      preLoaderRoute: typeof SurveySpotsIdSectionRouteImport
      parentRoute: typeof SurveyRoute
    }
  }
}

interface SurveyRouteChildren {
  SurveyAdminRoute: typeof SurveyAdminRoute
  SurveyIndexRoute: typeof SurveyIndexRoute
  SurveySpotsNewRoute: typeof SurveySpotsNewRoute
  SurveySpotsIdSectionRoute: typeof SurveySpotsIdSectionRoute
  SurveySpotsIdIndexRoute: typeof SurveySpotsIdIndexRoute
}

const SurveyRouteChildren: SurveyRouteChildren = {
  SurveyAdminRoute: SurveyAdminRoute,
  SurveyIndexRoute: SurveyIndexRoute,
  SurveySpotsNewRoute: SurveySpotsNewRoute,
  SurveySpotsIdSectionRoute: SurveySpotsIdSectionRoute,
  SurveySpotsIdIndexRoute: SurveySpotsIdIndexRoute,
}

const SurveyRouteWithChildren =
  SurveyRoute._addFileChildren(SurveyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurveyRoute: SurveyRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
