/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SurveyIndexRouteImport } from './routes/survey.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIndexRoute = SurveyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survey': typeof SurveyRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/survey/': typeof SurveyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/survey': typeof SurveyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/survey': typeof SurveyRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/survey/': typeof SurveyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/survey' | '/invite/$token' | '/survey/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invite/$token' | '/survey'
  id: '__root__' | '/' | '/survey' | '/invite/$token' | '/survey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurveyRoute: typeof SurveyRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/': {
      id: '/survey/'
      path: '/'
      fullPath: '/survey/'
      preLoaderRoute: typeof SurveyIndexRouteImport
      parentRoute: typeof SurveyRoute
    }
  }
}

interface SurveyRouteChildren {
  SurveyIndexRoute: typeof SurveyIndexRoute
}

const SurveyRouteChildren: SurveyRouteChildren = {
  SurveyIndexRoute: SurveyIndexRoute,
}

const SurveyRouteWithChildren =
  SurveyRoute._addFileChildren(SurveyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurveyRoute: SurveyRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
