// Generated from docs/design/surveyor-copy.md by `bun run copy:gen`, which
// then formats it with Biome so lint stays clean. Do not edit.

export const COPY = {
  "app.name": "Perch",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.back": "Back",
  "common.retry": "Retry",
  "common.discard": "Discard",
  "common.optional": "Optional",
  "common.required": "Required",
  "common.unknown": "Not sure",
  "common.yes": "Yes",
  "common.no": "No",
  "error.generic": "That didn't work. Try again in a minute.",
  "error.network_admin": "Admin actions need a connection.",
  "sync.all_synced": "All synced",
  "sync.pending": "{count} waiting to sync",
  "sync.syncing": "Syncing {count}",
  "sync.offline": "Offline, saving on this phone",
  "sync.failed": "{count} didn't save",
  "sync.unreadable": "{count} changes can't be read",
  "sync.sheet.title": "Changes on this phone",
  "sync.sheet.empty": "Nothing waiting. Everything is on the server.",
  "sync.sheet.item_pending": "Waiting: {what}",
  "sync.sheet.item_failed": "Didn't save: {what}",
  "sync.sheet.item_conflict": "Changed by someone else: {what}",
  "sync.sheet.local_only": "Not on the server yet. It will be created when you're back online.",
  "sync.sheet.other_phone_warning":
    "Changes stay on this phone. Signing in on another phone won't bring them along.",
  "sync.what.create": "New spot {name}",
  "sync.what.section": "{section} for {name}",
  "sync.what.verify": "Verified {name}",
  "sync.what.publish": "Publish {name}",
  "sync.what.photo": "Photo for {name}",
  "sync.what.review": "Review {name}",
  "sync.what.cover": "Cover photo for {name}",
  "sync.leave_warning": "{count} changes haven't synced yet. Leaving now keeps them on this phone.",
  "invite.title": "Join the Perch survey crew",
  "invite.body":
    "Perch is a campus study spot guide. Surveyors add and check the spots students see.",
  "invite.name.label": "Your name",
  "invite.name.helper": "Shown to other surveyors next to your edits.",
  "invite.join": "Join",
  "invite.joining": "Joining",
  "invite.ios.title": "On an iPhone?",
  "invite.ios.body":
    "Add Perch to your home screen first, then open this link inside that app. Safari and the app keep separate sign-ins.",
  "invite.offline": "Connect to the internet to join.",
  "invite.expired": "This link expired. Ask an admin for a new one.",
  "invite.used": "This link was already used. Ask an admin for a new one.",
  "invite.invalid": "This link doesn't work. Check it was copied in full, or ask for a new one.",
  "invite.name.required": "Add a name so others know who edited what.",
  "auth.expired.title": "Sign in again",
  "auth.expired.body": "Your sign-in on this phone ended. Ask an admin for a new link.",
  "nav.back_to_spots": "Back to spots",
  "nav.not_found.body": "Page not found.",
  "home.title": "Spots",
  "home.new_spot": "New spot",
  "home.admin": "Admin",
  "home.unreadable": "{count} changes can't be read",
  "home.stale.never": "Never checked",
  "home.empty.title": "No spots yet",
  "home.empty.body":
    "A spot is one place you'd tell a friend to study, like a reading room or a lounge. Start with the one you're standing in.",
  "new.title": "New spot",
  "new.building.label": "Building",
  "new.building.placeholder": "Search buildings",
  "new.floor.label": "Floor",
  "new.floor.helper": "As signed in the building, like 1, 2, B, or Mezzanine.",
  "new.official_name.label": "Name",
  "new.official_name.helper": "Use the sign on the door if there is one.",
  "new.common_name.label": "What students call it",
  "new.location.button": "Use my location",
  "new.location.pending": "Finding you",
  "new.location.done": "Located within {meters} m",
  "new.location.poor": "Location is rough ({meters} m). The building is enough.",
  "new.location.denied": "Location is off. The building is enough.",
  "new.directions.label": "How to get there",
  "new.directions.helper": "From the nearest entrance, in one or two sentences.",
  "new.directions.placeholder": "Main entrance, stairs to 3, left past the printers.",
  "new.save": "Create spot",
  "new.blocked": "Add a building, floor, and name to continue.",
  "spot.status.draft": "Draft",
  "spot.status.published": "Published",
  "spot.status.unreviewed": "Unreviewed",
  "spot.status.reviewed": "Reviewed by {name}",
  "spot.group.required": "Needed to publish",
  "spot.group.extras": "Extras",
  "spot.group.optional": "Optional now",
  "spot.section.missing": "Missing",
  "spot.section.partial": "Partly done",
  "spot.section.done": "Done",
  "spot.section.none": "None yet",
  "spot.section.not_set": "Not set",
  "spot.section.verified": "Checked {date}",
  "spot.section.verified_today": "Checked today",
  "spot.publish": "Publish",
  "spot.publish.blocked.title": "Can't publish yet",
  "spot.publish.blocked.item": "Missing: {field}",
  "spot.publish.queued": "Publish queued. It goes live after this phone syncs.",
  "spot.publish.done": "Published",
  "spot.review": "Looks right",
  "spot.review.done": "Marked reviewed",
  "spot.review.own": "You edited this last, so someone else reviews it.",
  "spot.unpublish": "Unpublish",
  "spot.unpublish.confirm.title": "Unpublish {name}?",
  "spot.unpublish.confirm.body": "Students won't see it after the next publish. The data stays.",
  "spot.unpublish.confirm.action": "Unpublish spot",
  "spot.failed.banner": "1 change didn't save",
  "spot.failed.banner_many": "{count} changes didn't save",
  "spot.conflict.banner": "Someone else changed this spot. Pick which version to keep.",
  "section.identity.name": "Basics",
  "section.access.name": "Access",
  "section.hours.name": "Hours",
  "section.seating.name": "Seating",
  "section.power.name": "Power and signal",
  "section.environment.name": "Noise and feel",
  "section.use_fit.name": "House rules",
  "section.amenities.name": "Nearby",
  "section.accessibility.name": "Accessibility",
  "section.late_night.name": "Late night",
  "section.estimates.name": "Busyness",
  "section.photos.name": "Photos",
  "editor.save": "Save",
  "editor.verify": "Nothing changed",
  "editor.save_next": "Save and next",
  "editor.progress.after": "{done} of {total} · After this: {section}",
  "editor.progress": "{done} of {total}",
  "editor.walk.done": "Checked 1 section",
  "editor.walk.done_many": "Checked {count} sections",
  "editor.walk.queued": "Checked 1 section, saved on this phone",
  "editor.walk.queued_many": "Checked {count} sections, saved on this phone",
  "editor.verify.done": "Marked as checked",
  "editor.verify.hours_missing": "Add hours for {term} before marking this checked.",
  "editor.saved": "Saved",
  "editor.saved_offline": "Saved on this phone",
  "editor.discard_changes.title": "Discard changes?",
  "editor.discard_changes.body": "Your edits to {section} won't be saved.",
  "editor.discard_changes.action": "Discard changes",
  "editor.discard_changes.keep": "Keep editing",
  "editor.invalid": "Fix the highlighted field to save.",
  "access.eligibility.label": "Who can use it",
  "access.eligibility.all_students": "Any student",
  "access.eligibility.residents_building": "Residents of one building",
  "access.eligibility.residents_quad": "Residents of one quad",
  "access.eligibility.grad_only": "Grad students only",
  "access.eligibility.department": "One department",
  "access.eligibility.public": "Anyone, not just students",
  "access.scope.label.building": "Which building",
  "access.scope.label.quad": "Which quad",
  "access.scope.label.department": "Which department",
  "access.eligibility.helper":
    "Check a sign or ask staff. If you're guessing, leave it unchecked below.",
  "access.verified.label": "I confirmed this",
  "access.verified.helper": "Unconfirmed access is never suggested to students.",
  "access.entry.label": "How you get in",
  "access.entry.open": "Walk in",
  "access.entry.card_swipe": "Card swipe",
  "access.entry.staffed_desk": "Staffed desk",
  "access.reservable.label": "Can be reserved",
  "access.reservation_url.label": "Booking link",
  "access.reservation_url.invalid": "Use a full link starting with https://",
  "hours.term": "For {term}",
  "hours.day.mon": "Mon",
  "hours.day.tue": "Tue",
  "hours.day.wed": "Wed",
  "hours.day.thu": "Thu",
  "hours.day.fri": "Fri",
  "hours.day.sat": "Sat",
  "hours.day.sun": "Sun",
  "hours.opens": "Opens",
  "hours.closes": "Closes",
  "hours.closed": "Closed",
  "hours.next_day": "next day",
  "hours.copy_weekdays": "Copy Monday to weekdays",
  "hours.exam.toggle": "Different hours during finals",
  "hours.exam.title": "Finals hours",
  "hours.helper": "Use the posted hours. If none are posted, check the building's website.",
  "hours.invalid.same_time":
    "Opens and closes can't be the same time. Mark the day closed or 24 hours.",
  "hours.all_day": "Open 24 hours",
  "hours.mode.hours": "Hours",
  "hours.mode.closed": "Closed",
  "hours.mode.all_day": "24 hours",
  "hours.summary": "{opens} to {closes}",
  "hours.summary_next": "{opens} to {closes} next day",
  "hours.summary_unset": "Set the times",
  "seating.seat_count.label": "Seats",
  "seating.seat_count.helper":
    "Count chairs you could sit in for an hour. Rough is fine for big rooms.",
  "seating.seat_count.invalid": "Enter a number of seats above 0.",
  "seating.types.label": "Kinds of seats",
  "seating.type.table_chair": "Table and chair",
  "seating.type.carrel": "Desk carrel",
  "seating.type.soft": "Couch or armchair",
  "seating.type.booth": "Booth",
  "seating.type.standing": "Standing desk",
  "seating.tables.label": "Tables",
  "seating.table.large_shared": "Big shared tables",
  "seating.table.small_2_4": "Small tables for 2 to 4",
  "seating.table.individual": "Single desks",
  "seating.max_group.label": "Biggest group that can sit together",
  "seating.spread_out.label": "Room to spread out",
  "power.outlets.label": "Seats near an outlet",
  "power.outlets.helper": "About how many seats can reach a working outlet with a normal cable.",
  "power.outlets.value": "{percent}%",
  "power.usb.label": "USB ports",
  "power.wifi.label": "Wifi speed (Mbps)",
  "power.wifi.helper": "Run a speed test and enter the download number.",
  "power.cell.label": "Cell signal",
  "power.cell.poor": "Poor",
  "power.cell.ok": "OK",
  "power.cell.good": "Good",
  "env.noise.label": "Noise rule",
  "env.noise.helper": "What the space expects, not how loud it is right now.",
  "env.noise.silent": "Silent",
  "env.noise.quiet": "Quiet",
  "env.noise.conversational": "Talking is fine",
  "env.noise.group_friendly": "Groups welcome",
  "env.light.natural": "Daylight",
  "env.lighting.label": "Lighting",
  "env.lighting.dim": "Dim",
  "env.lighting.moderate": "Medium",
  "env.lighting.bright": "Bright",
  "env.temperature.label": "Temperature",
  "env.temperature.cold": "Cold",
  "env.temperature.neutral": "Fine",
  "env.temperature.warm": "Warm",
  "env.temperature_consistent.label": "Same temperature all day",
  "env.windows.label": "Windows with a view",
  "use.food.label": "Food and drink",
  "use.food.none": "Nothing",
  "use.food.covered_drinks": "Covered drinks",
  "use.food.food_ok": "Food is fine",
  "use.group.label": "Group work",
  "use.group.helper": "Can a group talk through a project here without getting shushed?",
  "use.calls.label": "Phone calls",
  "use.calls.not_allowed": "Not allowed",
  "use.calls.allowed_impractical": "Allowed, but awkward",
  "use.calls.allowed": "Fine",
  "use.whiteboard.label": "Whiteboard",
  "amenity.helper": "Walking minutes from the spot. Leave blank if you don't know.",
  "amenity.bathroom": "Bathroom",
  "amenity.water": "Water",
  "amenity.coffee_food": "Coffee or food",
  "amenity.printer": "Printer",
  "amenity.microwave": "Microwave",
  "amenity.late_food": "Food after 10pm",
  "amenity.minutes": "{minutes} min",
  "a11y.step_free": "Step-free route in",
  "a11y.elevator": "Elevator to this floor",
  "a11y.seating": "Accessible seating",
  "late.past_midnight": "Open past midnight",
  "late.staffed": "Staff around late",
  "late.lit_route": "Lit walk to the dorms",
  "estimates.helper": "Your best guess for a normal week. Real counts replace these later.",
  "estimates.weekday": "Weekdays",
  "estimates.weekend": "Weekends",
  "estimates.morning": "Morning",
  "estimates.afternoon": "Afternoon",
  "estimates.evening": "Evening",
  "estimates.night": "Night",
  "estimates.bucket.unset": "Not set",
  "estimates.bucket.empty": "Empty",
  "estimates.bucket.some": "Some seats",
  "estimates.bucket.filling": "Filling",
  "estimates.bucket.nearly_full": "Nearly full",
  "estimates.bucket.full": "Full",
  "estimates.tap_hint": "Tap a box to change it.",
  "photos.take": "Take photo",
  "photos.choose": "Choose from library",
  "photos.checklist.title": "A good cover photo",
  "photos.checklist.landscape": "Hold the phone sideways",
  "photos.checklist.wide": "Show the whole space, not one table",
  "photos.checklist.light": "Lights on or daylight",
  "photos.checklist.no_people": "No faces you could recognize",
  "photos.checklist.no_logos": "Don't make a university logo the subject",
  "photos.checklist.ok": "Got it",
  "photos.cover": "Use as cover",
  "photos.is_cover": "Cover",
  "photos.awaiting": "Waiting for approval",
  "photos.approved": "Approved",
  "photos.processing": "Shrinking photo",
  "photos.too_big": "That photo is still too large after shrinking. Try another shot.",
  "photos.unreadable": "Couldn't read that image. Try taking it again.",
  "photos.empty": "No photos yet. Students see the cover first.",
  "photos.unavailable": "Image unavailable",
  "conflict.title": "Two versions of {section}",
  "conflict.body": "{name} changed this while your edit was waiting. Pick which version to keep.",
  "conflict.body_unknown":
    "Someone else changed this while your edit was waiting. Pick which version to keep.",
  "conflict.yours": "Yours",
  "conflict.theirs": "On the server",
  "conflict.keep_mine": "Keep mine",
  "conflict.keep_theirs": "Keep theirs",
  "conflict.resolved": "Kept your version. It will sync again.",
  "conflict.dropped": "Kept their version. Your edit was discarded.",
  "failed.title": "This change didn't save",
  "failed.body.publish": "Still missing: {fields}",
  "failed.retry": "Try again",
  "failed.discard": "Discard change",
  "failed.discard.confirm": "This removes your change from this phone. It can't be undone.",
  "admin.title": "Admin",
  "admin.invite.title": "Invite a surveyor",
  "admin.invite.role.surveyor": "Surveyor",
  "admin.invite.role.admin": "Admin",
  "admin.invite.create": "Create invite link",
  "admin.invite.created": "Link works once and expires in 48 hours.",
  "admin.invite.copy": "Copy link",
  "admin.invite.copied": "Link copied",
  "admin.invite.copy_failed": "Couldn't copy. Select the link and copy it by hand.",
  "admin.invite.relogin": "New sign-in link",
  "admin.surveyors.title": "Surveyors",
  "admin.surveyors.empty": "Just you so far.",
  "admin.surveyors.admin_badge": "Admin",
  "admin.surveyor.actions": "Actions for {name}",
  "admin.revoke": "Remove access",
  "admin.revoke.confirm.title": "Remove {name}?",
  "admin.revoke.confirm.body": "They're signed out on every phone. Their published edits stay.",
  "admin.revoke.confirm.action": "Remove access",
  "admin.revoke.done": "{name} removed",
  "admin.publish.title": "Student data",
  "admin.publish.last": "Last published {time}",
  "admin.publish.never": "Not published yet",
  "admin.publish.dirty": "Changes waiting to publish",
  "admin.publish.clean": "Up to date",
  "admin.publish.first": "1 spot waiting for the first publish",
  "admin.publish.first_many": "{count} spots waiting for the first publish",
  "admin.publish.now": "Publish now",
  "admin.publish.running": "Publishing",
  "admin.publish.waiting": "Another publish has the lock until {time}",
  "admin.publish.waiting_self": "Last publish got no answer. Retry after {time}",
  "admin.publish.error": "Last publish failed: {reason}",
  "admin.publish.warnings.title": "Skipped spots",
  "admin.publish.warning.item": "{name}: {reason}",
  "admin.photos.title": "Photos to approve",
  "admin.photos.empty": "No photos waiting.",
  "admin.photos.from": "{spot}, from {name}",
  "admin.photos.approve": "Approve",
  "admin.photos.reject": "Reject",
  "admin.photos.reject.confirm": "Delete this photo? It won't be published.",
  "sync.checking": "Checking this phone",
  "sync.short.checking": "Checking",
  "sync.short.pending": "{count} waiting",
  "sync.short.offline": "Offline",
  "sync.short.failed": "{count} not saved",
  "sync.short.unreadable": "{count} unreadable",
  "sync.short.signed_out": "Signed out",
  "sync.unreadable_one": "1 change can't be read",
  "auth.misconfigured": "This build has no server address. Ask whoever sent you the link.",
  "sync.leave_warning_one": "1 change hasn't synced yet. Leaving now keeps it on this phone.",
  "sync.sheet.unreadable_item": "A saved change this app can't read",
  "sync.sheet.unreadable_help":
    "These came from a newer or damaged copy of the app. Discard them if they stay.",
  "sync.sheet.open_spot": "Open spot",
  "sync.sheet.open_spot_named": "Open spot {name}",
  "home.unreadable_one": "1 change can't be read",
  "home.drafts.empty": "No drafts.",
  "home.offline_first":
    "The spot list loads once you're online. New spots still save on this phone.",
  "spot.section.on_phone": "On this phone",
  "spot.section.syncing": "Syncing",
  "spot.section.failed": "Didn't save",
  "spot.section.conflict": "Two versions",
  "spot.publish.queued_chip": "Publish queued",
  "spot.review.queued": "Review queued",
  "spot.not_found": "This spot isn't on this phone. Go online to load it.",
  "field.directions": "How to get there",
  "field.eligibility": "Who can use it",
  "field.seat_count": "Seats",
  "field.outlet_coverage_pct": "Seats near an outlet",
  "field.noise_policy": "Noise rule",
  "field.group_work_ok": "Group work",
  "field.food_policy": "Food and drink",
  "field.last_verified": "A checked section",
  "failed.reason.photo_missing": "The photo is no longer on this phone. Take it again.",
  "failed.reason.photo_unreadable":
    "This phone could not read the photo. Try again, or take it again.",
  "failed.reason.bad_response":
    "The server's answer couldn't be read, so this can't be sent again. Discard it and redo it.",
  "failed.reason.no_base_version":
    "This phone lost track of the spot's version. Discard it and save the section again.",
  "failed.reason.forbidden": "Your account can't make this change.",
  "failed.reason.not_found": "This spot is no longer on the server.",
  "failed.reason.invalid_request":
    "Some values weren't accepted. Open the section, check it, and save again.",
  "failed.reason.slug_taken": "Another spot already has this name. Change the name in Basics.",
  "failed.reason.unknown_building":
    "That building isn't on the server's list. Pick it again in Basics.",
  "failed.reason.unknown_term": "The term changed. Open Hours and save again.",
  "failed.reason.photo_too_large": "The photo was too large for the server. Take it again.",
  "failed.reason.photo_type": "The server only takes JPEG photos. Take it again.",
  "failed.reason.write_id_reused":
    "This change clashed with an older one. Discard it and make it again.",
  "editor.unpublish.title": "This takes the spot off the student app",
  "editor.unpublish.body":
    "With {fields} empty, students stop seeing this spot after the next publish.",
  "editor.unpublish.action": "Save anyway",
  "identity.outdoor.label": "Outdoors",
  "identity.seasonal.label": "Only open some seasons",
  "invite.relogin.title": "Sign in on this phone",
  "invite.relogin.body": "This link signs you back in. Your name and role stay the same.",
  "invite.relogin.action": "Sign in",
  "invite.switch.title": "Unsynced changes from {name}",
  "invite.switch.body":
    "This phone holds changes {name} has not synced. Cancel keeps them, but this link is used up, so you will need a new one to join as {new}.",
  "invite.switch.discard": "Discard their changes and join",
  "photos.approve": "Approve",
  "photos.approve.done": "Photo approved",
  "photos.online_only": "Approving needs a connection.",
  "photos.not_synced": "Not synced yet",
  "photos.cover.wait": "Sync first to use this as cover",
  "estimates.cell": "{day}, {block}: {bucket}",
  "update.ready": "A new version of Perch is ready.",
  "update.reload": "Reload",
  "admin.invite.relogin.created": "Sign-in link for {name}. Works once, for 48 hours.",
  "admin.surveyors.inactive": "No access",
  "admin.publish.warning.missing": "missing {fields}",
  "admin.publish.warning.invalid": "has a value the student app can't use",
  "admin.publish.warning.hours": "has hours the student app can't read",
  "common.close": "Close",
  "common.open": "Open",
  "common.loading": "Loading",
  "common.less": "Less",
  "common.more": "More",
  "unit.minutes": "min",
  "unit.percent": "%",
  "new.building.none": "No building matches.",
  "common.save_failed": "This phone couldn't save that. Check what you have, then try again.",
  "spot.conflict.open": "Open the conflict",
  "spot.failed.open": "Open the unsaved changes",
  "photos.alt": "Photo of this spot",
  "new.building.offline": "The building list loads once you're online.",
  "theme.label": "Theme",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "theme.system": "System",
  "common.actions": "Actions",
  "home.filter.label": "Show",
  "home.filter.all": "All",
  "home.filter.attention": "Needs you",
  "home.filter.drafts": "Drafts",
  "home.filter.due": "Due",
  "home.search.label": "Search spots",
  "home.group.all": "All spots",
  "home.group.attention": "Needs you",
  "home.group.drafts": "Drafts",
  "home.group.due": "Due",
  "home.empty.attention": "Nothing needs you.",
  "home.empty.due": "Nothing is due.",
  "home.empty.search": "No spots match.",
  "home.keep_going": "Keep going",
  "home.keep_going.next": "Keep going · Next: {section} · {count} left",
  "home.keep_going.ready": "Keep going · Ready to publish",
  "home.fact.conflict": "Conflict",
  "home.fact.failed": "Didn't save",
  "home.fact.unreviewed": "Unreviewed",
  "home.fact.unreviewed_by": "Edited by {name}",
  "home.fact.hours": "No {term} hours",
  "home.fact.progress": "{done}/{total}",
  "home.checked": "Checked {date}",
  "home.fact.draft": "Draft",
  "progress.label": "{done} of {total} done",
  "spot.progress.next": "{done} of {total} · Next: {section}",
  "spot.progress.complete": "{done} of {total} done",
  "spot.next": "Next: {section}",
  "spot.meta.floor": "Floor {floor}",
  "spot.meta.place": "{building} · Floor {floor}",
  "spot.publish.blocked.reason": "Can't publish yet: {count} missing",
  "spot.actions.next_missing": "Open next missing: {section}",
  "spot.actions.add_photo": "Add a photo",
  "spot.actions.walk": "Check each section",
  "spot.actions.walk.hint": "Open every needed section, one after another",
  "spot.fact.seats": "{count} seats",
  "spot.fact.outlets": "{percent}% near outlets",
  "spot.fact.hours": "{term} hours",
  "spot.fact.blocks": "{count} of {total} blocks",
  "spot.fact.photos_one": "1 photo",
  "spot.fact.photos": "{count} photos",
} as const;

export const COPY_MAX = {
  "app.name": 10,
  "common.save": 12,
  "common.cancel": 12,
  "common.back": 12,
  "common.retry": 12,
  "common.discard": 12,
  "common.optional": 12,
  "common.required": 12,
  "common.unknown": 16,
  "common.yes": 6,
  "common.no": 6,
  "error.generic": 60,
  "error.network_admin": 50,
  "sync.all_synced": 20,
  "sync.pending": 24,
  "sync.syncing": 20,
  "sync.offline": 32,
  "sync.failed": 22,
  "sync.unreadable": 30,
  "sync.sheet.title": 30,
  "sync.sheet.empty": 60,
  "sync.sheet.item_pending": 60,
  "sync.sheet.item_failed": 60,
  "sync.sheet.item_conflict": 60,
  "sync.sheet.local_only": 90,
  "sync.sheet.other_phone_warning": 100,
  "sync.what.create": 50,
  "sync.what.section": 50,
  "sync.what.verify": 50,
  "sync.what.publish": 50,
  "sync.what.photo": 50,
  "sync.what.review": 50,
  "sync.what.cover": 50,
  "sync.leave_warning": 90,
  "invite.title": 32,
  "invite.body": 100,
  "invite.name.label": 20,
  "invite.name.helper": 60,
  "invite.join": 12,
  "invite.joining": 12,
  "invite.ios.title": 20,
  "invite.ios.body": 140,
  "invite.offline": 40,
  "invite.expired": 60,
  "invite.used": 64,
  "invite.invalid": 90,
  "invite.name.required": 60,
  "auth.expired.title": 20,
  "auth.expired.body": 110,
  "nav.back_to_spots": 20,
  "nav.not_found.body": 40,
  "home.title": 12,
  "home.new_spot": 14,
  "home.admin": 10,
  "home.unreadable": 34,
  "home.stale.never": 20,
  "home.empty.title": 20,
  "home.empty.body": 140,
  "new.title": 14,
  "new.building.label": 16,
  "new.building.placeholder": 20,
  "new.floor.label": 10,
  "new.floor.helper": 70,
  "new.official_name.label": 10,
  "new.official_name.helper": 50,
  "new.common_name.label": 26,
  "new.location.button": 20,
  "new.location.pending": 16,
  "new.location.done": 30,
  "new.location.poor": 60,
  "new.location.denied": 50,
  "new.directions.label": 20,
  "new.directions.helper": 60,
  "new.directions.placeholder": 60,
  "new.save": 16,
  "new.blocked": 50,
  "spot.status.draft": 10,
  "spot.status.published": 12,
  "spot.status.unreviewed": 12,
  "spot.status.reviewed": 30,
  "spot.group.required": 20,
  "spot.group.extras": 10,
  "spot.group.optional": 16,
  "spot.section.missing": 10,
  "spot.section.partial": 12,
  "spot.section.done": 8,
  "spot.section.none": 10,
  "spot.section.not_set": 10,
  "spot.section.verified": 16,
  "spot.section.verified_today": 16,
  "spot.publish": 12,
  "spot.publish.blocked.title": 20,
  "spot.publish.blocked.item": 40,
  "spot.publish.queued": 60,
  "spot.publish.done": 12,
  "spot.review": 14,
  "spot.review.done": 18,
  "spot.review.own": 60,
  "spot.unpublish": 12,
  "spot.unpublish.confirm.title": 36,
  "spot.unpublish.confirm.body": 70,
  "spot.unpublish.confirm.action": 16,
  "spot.failed.banner": 26,
  "spot.failed.banner_many": 30,
  "spot.conflict.banner": 64,
  "section.identity.name": 12,
  "section.access.name": 12,
  "section.hours.name": 12,
  "section.seating.name": 12,
  "section.power.name": 18,
  "section.environment.name": 16,
  "section.use_fit.name": 14,
  "section.amenities.name": 12,
  "section.accessibility.name": 14,
  "section.late_night.name": 12,
  "section.estimates.name": 12,
  "section.photos.name": 12,
  "editor.save": 10,
  "editor.verify": 18,
  "editor.save_next": 16,
  "editor.progress.after": 46,
  "editor.progress": 10,
  "editor.walk.done": 20,
  "editor.walk.done_many": 26,
  "editor.walk.queued": 42,
  "editor.walk.queued_many": 48,
  "editor.verify.done": 20,
  "editor.verify.hours_missing": 60,
  "editor.saved": 10,
  "editor.saved_offline": 22,
  "editor.discard_changes.title": 20,
  "editor.discard_changes.body": 50,
  "editor.discard_changes.action": 18,
  "editor.discard_changes.keep": 16,
  "editor.invalid": 40,
  "access.eligibility.label": 18,
  "access.eligibility.all_students": 16,
  "access.eligibility.residents_building": 28,
  "access.eligibility.residents_quad": 24,
  "access.eligibility.grad_only": 20,
  "access.eligibility.department": 18,
  "access.eligibility.public": 28,
  "access.scope.label.building": 18,
  "access.scope.label.quad": 14,
  "access.scope.label.department": 18,
  "access.eligibility.helper": 80,
  "access.verified.label": 20,
  "access.verified.helper": 60,
  "access.entry.label": 16,
  "access.entry.open": 10,
  "access.entry.card_swipe": 12,
  "access.entry.staffed_desk": 14,
  "access.reservable.label": 18,
  "access.reservation_url.label": 14,
  "access.reservation_url.invalid": 44,
  "hours.term": 24,
  "hours.day.mon": 4,
  "hours.day.tue": 4,
  "hours.day.wed": 4,
  "hours.day.thu": 4,
  "hours.day.fri": 4,
  "hours.day.sat": 4,
  "hours.day.sun": 4,
  "hours.opens": 8,
  "hours.closes": 8,
  "hours.closed": 8,
  "hours.next_day": 10,
  "hours.copy_weekdays": 26,
  "hours.exam.toggle": 30,
  "hours.exam.title": 14,
  "hours.helper": 80,
  "hours.invalid.same_time": 80,
  "hours.all_day": 16,
  "hours.mode.hours": 8,
  "hours.mode.closed": 8,
  "hours.mode.all_day": 10,
  "hours.summary": 24,
  "hours.summary_next": 34,
  "hours.summary_unset": 16,
  "seating.seat_count.label": 8,
  "seating.seat_count.helper": 80,
  "seating.seat_count.invalid": 40,
  "seating.types.label": 16,
  "seating.type.table_chair": 16,
  "seating.type.carrel": 12,
  "seating.type.soft": 18,
  "seating.type.booth": 8,
  "seating.type.standing": 14,
  "seating.tables.label": 8,
  "seating.table.large_shared": 18,
  "seating.table.small_2_4": 24,
  "seating.table.individual": 14,
  "seating.max_group.label": 36,
  "seating.spread_out.label": 20,
  "power.outlets.label": 22,
  "power.outlets.helper": 80,
  "power.outlets.value": 6,
  "power.usb.label": 10,
  "power.wifi.label": 18,
  "power.wifi.helper": 54,
  "power.cell.label": 12,
  "power.cell.poor": 6,
  "power.cell.ok": 4,
  "power.cell.good": 6,
  "env.noise.label": 12,
  "env.noise.helper": 60,
  "env.noise.silent": 8,
  "env.noise.quiet": 8,
  "env.noise.conversational": 16,
  "env.noise.group_friendly": 16,
  "env.light.natural": 10,
  "env.lighting.label": 10,
  "env.lighting.dim": 6,
  "env.lighting.moderate": 8,
  "env.lighting.bright": 8,
  "env.temperature.label": 12,
  "env.temperature.cold": 6,
  "env.temperature.neutral": 6,
  "env.temperature.warm": 6,
  "env.temperature_consistent.label": 26,
  "env.windows.label": 20,
  "use.food.label": 16,
  "use.food.none": 10,
  "use.food.covered_drinks": 16,
  "use.food.food_ok": 14,
  "use.group.label": 12,
  "use.group.helper": 70,
  "use.calls.label": 12,
  "use.calls.not_allowed": 12,
  "use.calls.allowed_impractical": 22,
  "use.calls.allowed": 6,
  "use.whiteboard.label": 12,
  "amenity.helper": 64,
  "amenity.bathroom": 10,
  "amenity.water": 8,
  "amenity.coffee_food": 16,
  "amenity.printer": 10,
  "amenity.microwave": 10,
  "amenity.late_food": 16,
  "amenity.minutes": 8,
  "a11y.step_free": 20,
  "a11y.elevator": 24,
  "a11y.seating": 20,
  "late.past_midnight": 20,
  "late.staffed": 18,
  "late.lit_route": 22,
  "estimates.helper": 70,
  "estimates.weekday": 10,
  "estimates.weekend": 10,
  "estimates.morning": 8,
  "estimates.afternoon": 10,
  "estimates.evening": 8,
  "estimates.night": 6,
  "estimates.bucket.unset": 8,
  "estimates.bucket.empty": 8,
  "estimates.bucket.some": 10,
  "estimates.bucket.filling": 8,
  "estimates.bucket.nearly_full": 12,
  "estimates.bucket.full": 6,
  "estimates.tap_hint": 26,
  "photos.take": 12,
  "photos.choose": 20,
  "photos.checklist.title": 20,
  "photos.checklist.landscape": 26,
  "photos.checklist.wide": 36,
  "photos.checklist.light": 22,
  "photos.checklist.no_people": 30,
  "photos.checklist.no_logos": 42,
  "photos.checklist.ok": 8,
  "photos.cover": 14,
  "photos.is_cover": 8,
  "photos.awaiting": 22,
  "photos.approved": 10,
  "photos.processing": 18,
  "photos.too_big": 70,
  "photos.unreadable": 50,
  "photos.empty": 50,
  "photos.unavailable": 20,
  "conflict.title": 32,
  "conflict.body": 90,
  "conflict.body_unknown": 84,
  "conflict.yours": 8,
  "conflict.theirs": 14,
  "conflict.keep_mine": 12,
  "conflict.keep_theirs": 12,
  "conflict.resolved": 44,
  "conflict.dropped": 50,
  "failed.title": 26,
  "failed.body.publish": 60,
  "failed.retry": 12,
  "failed.discard": 16,
  "failed.discard.confirm": 70,
  "admin.title": 10,
  "admin.invite.title": 20,
  "admin.invite.role.surveyor": 10,
  "admin.invite.role.admin": 8,
  "admin.invite.create": 20,
  "admin.invite.created": 50,
  "admin.invite.copy": 12,
  "admin.invite.copied": 14,
  "admin.invite.copy_failed": 60,
  "admin.invite.relogin": 18,
  "admin.surveyors.title": 12,
  "admin.surveyors.empty": 20,
  "admin.surveyors.admin_badge": 8,
  "admin.surveyor.actions": 34,
  "admin.revoke": 16,
  "admin.revoke.confirm.title": 30,
  "admin.revoke.confirm.body": 70,
  "admin.revoke.confirm.action": 16,
  "admin.revoke.done": 30,
  "admin.publish.title": 14,
  "admin.publish.last": 30,
  "admin.publish.never": 20,
  "admin.publish.dirty": 28,
  "admin.publish.clean": 12,
  "admin.publish.first": 40,
  "admin.publish.first_many": 44,
  "admin.publish.now": 14,
  "admin.publish.running": 12,
  "admin.publish.waiting": 52,
  "admin.publish.waiting_self": 60,
  "admin.publish.error": 70,
  "admin.publish.warnings.title": 16,
  "admin.publish.warning.item": 80,
  "admin.photos.title": 18,
  "admin.photos.empty": 20,
  "admin.photos.from": 40,
  "admin.photos.approve": 10,
  "admin.photos.reject": 8,
  "admin.photos.reject.confirm": 50,
  "sync.checking": 24,
  "sync.short.checking": 10,
  "sync.short.pending": 14,
  "sync.short.offline": 10,
  "sync.short.failed": 16,
  "sync.short.unreadable": 16,
  "sync.short.signed_out": 12,
  "sync.unreadable_one": 30,
  "auth.misconfigured": 70,
  "sync.leave_warning_one": 90,
  "sync.sheet.unreadable_item": 40,
  "sync.sheet.unreadable_help": 90,
  "sync.sheet.open_spot": 12,
  "sync.sheet.open_spot_named": 60,
  "home.unreadable_one": 34,
  "home.drafts.empty": 14,
  "home.offline_first": 90,
  "spot.section.on_phone": 14,
  "spot.section.syncing": 10,
  "spot.section.failed": 12,
  "spot.section.conflict": 14,
  "spot.publish.queued_chip": 16,
  "spot.review.queued": 16,
  "spot.not_found": 60,
  "field.directions": 20,
  "field.eligibility": 18,
  "field.seat_count": 10,
  "field.outlet_coverage_pct": 22,
  "field.noise_policy": 12,
  "field.group_work_ok": 12,
  "field.food_policy": 16,
  "field.last_verified": 20,
  "failed.reason.photo_missing": 60,
  "failed.reason.photo_unreadable": 70,
  "failed.reason.bad_response": 100,
  "failed.reason.no_base_version": 90,
  "failed.reason.forbidden": 40,
  "failed.reason.not_found": 40,
  "failed.reason.invalid_request": 80,
  "failed.reason.slug_taken": 70,
  "failed.reason.unknown_building": 70,
  "failed.reason.unknown_term": 50,
  "failed.reason.photo_too_large": 60,
  "failed.reason.photo_type": 60,
  "failed.reason.write_id_reused": 80,
  "editor.unpublish.title": 44,
  "editor.unpublish.body": 100,
  "editor.unpublish.action": 14,
  "identity.outdoor.label": 10,
  "identity.seasonal.label": 24,
  "invite.relogin.title": 24,
  "invite.relogin.body": 70,
  "invite.relogin.action": 10,
  "invite.switch.title": 40,
  "invite.switch.body": 150,
  "invite.switch.discard": 34,
  "photos.approve": 10,
  "photos.approve.done": 16,
  "photos.online_only": 32,
  "photos.not_synced": 16,
  "photos.cover.wait": 32,
  "estimates.cell": 40,
  "update.ready": 40,
  "update.reload": 10,
  "admin.invite.relogin.created": 60,
  "admin.surveyors.inactive": 10,
  "admin.publish.warning.missing": 60,
  "admin.publish.warning.invalid": 44,
  "admin.publish.warning.hours": 44,
  "common.close": 10,
  "common.open": 8,
  "common.loading": 10,
  "common.less": 6,
  "common.more": 6,
  "unit.minutes": 4,
  "unit.percent": 2,
  "new.building.none": 24,
  "common.save_failed": 70,
  "spot.conflict.open": 20,
  "spot.failed.open": 26,
  "photos.alt": 20,
  "new.building.offline": 50,
  "theme.label": 8,
  "theme.light": 8,
  "theme.dark": 8,
  "theme.system": 8,
  "common.actions": 10,
  "home.filter.label": 8,
  "home.filter.all": 6,
  "home.filter.attention": 12,
  "home.filter.drafts": 8,
  "home.filter.due": 6,
  "home.search.label": 16,
  "home.group.all": 14,
  "home.group.attention": 12,
  "home.group.drafts": 8,
  "home.group.due": 6,
  "home.empty.attention": 24,
  "home.empty.due": 20,
  "home.empty.search": 20,
  "home.keep_going": 14,
  "home.keep_going.next": 56,
  "home.keep_going.ready": 36,
  "home.fact.conflict": 10,
  "home.fact.failed": 12,
  "home.fact.unreviewed": 12,
  "home.fact.unreviewed_by": 30,
  "home.fact.hours": 24,
  "home.fact.progress": 6,
  "home.checked": 20,
  "home.fact.draft": 8,
  "progress.label": 20,
  "spot.progress.next": 40,
  "spot.progress.complete": 20,
  "spot.next": 30,
  "spot.meta.floor": 16,
  "spot.meta.place": 40,
  "spot.publish.blocked.reason": 36,
  "spot.actions.next_missing": 44,
  "spot.actions.add_photo": 14,
  "spot.actions.walk": 20,
  "spot.actions.walk.hint": 44,
  "spot.fact.seats": 12,
  "spot.fact.outlets": 22,
  "spot.fact.hours": 22,
  "spot.fact.blocks": 20,
  "spot.fact.photos_one": 10,
  "spot.fact.photos": 12,
} as const satisfies Record<keyof typeof COPY, number>;
