import { paletteVariables, sharedVariables, type Tokens } from "@perch/ui-logic";

function block(selector: string, vars: Record<string, string>, indent = ""): string {
  const lines = Object.entries(vars).map(([name, value]) => `${indent}  ${name}: ${value};`);
  return `${indent}${selector} {\n${lines.join("\n")}\n${indent}}`;
}

/**
 * The token stylesheet: light on :root, dark when data-theme says so, and dark
 * from the OS only when no data-theme is set (the "system" pref). The inline
 * boot script in index.html sets data-theme before this loads.
 */
export function themeCss(t: Tokens): string {
  const dark = { ...paletteVariables(t.color.dark), "color-scheme": "dark" };
  return `${[
    "/* Generated by `bun run tokens:gen` from packages/ui-logic/src/tokens.ts. Do not edit. */",
    block(":root", {
      ...sharedVariables(t),
      ...paletteVariables(t.color.light),
      "color-scheme": "light",
    }),
    block(':root[data-theme="dark"]', dark),
    `@media (prefers-color-scheme: dark) {\n${block(":root:not([data-theme])", dark, "  ")}\n}`,
  ].join("\n\n")}\n`;
}
